export interface Exercise {
  id: string;
  name: string;
  category: ExerciseCategory;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  equipment: string[];
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  type: "strength" | "cardio" | "flexibility" | "plyometric";
  description: string;
  tips: string[];
  sets?: string;
  reps?: string;
  duration?: string;
}

export type ExerciseCategory =
  | "chest"
  | "back"
  | "shoulders"
  | "arms"
  | "legs"
  | "glutes"
  | "core"
  | "cardio"
  | "full_body"
  | "flexibility";

export const EXERCISE_CATEGORIES: { id: ExerciseCategory; label: string; icon: string }[] = [
  { id: "chest", label: "Chest", icon: "shield" },
  { id: "back", label: "Back", icon: "layers" },
  { id: "shoulders", label: "Shoulders", icon: "wind" },
  { id: "arms", label: "Arms", icon: "zap" },
  { id: "legs", label: "Legs", icon: "activity" },
  { id: "glutes", label: "Glutes", icon: "anchor" },
  { id: "core", label: "Core", icon: "circle" },
  { id: "cardio", label: "Cardio", icon: "heart" },
  { id: "full_body", label: "Full Body", icon: "user" },
  { id: "flexibility", label: "Flexibility", icon: "rotate-cw" },
];

export const EXERCISES: Exercise[] = [
  // ── CHEST ──────────────────────────────────────────────────────────────────
  {
    id: "bench_press",
    name: "Barbell Bench Press",
    category: "chest",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Triceps", "Front Deltoids"],
    equipment: ["barbell", "bench"],
    difficulty: "Intermediate",
    type: "strength",
    description: "The king of chest exercises. Lie flat on the bench, grip the bar slightly wider than shoulder-width, lower it to your mid-chest and press up powerfully.",
    tips: ["Retract your shoulder blades into the bench", "Keep your feet flat on the floor", "Don't bounce the bar off your chest", "Maintain a slight arch in your lower back"],
    sets: "3–5", reps: "5–10",
  },
  {
    id: "incline_bench_press",
    name: "Incline Bench Press",
    category: "chest",
    primaryMuscles: ["Upper Pectorals"],
    secondaryMuscles: ["Front Deltoids", "Triceps"],
    equipment: ["barbell", "bench"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Set the bench to 30–45°. Targets the upper chest for a fuller, more developed look.",
    tips: ["Keep elbows at ~75° angle", "Don't flare elbows too wide", "Lower bar to upper chest", "Control the eccentric"],
    sets: "3–4", reps: "8–12",
  },
  {
    id: "dumbbell_fly",
    name: "Dumbbell Fly",
    category: "chest",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Front Deltoids"],
    equipment: ["dumbbells", "bench"],
    difficulty: "Beginner",
    type: "strength",
    description: "Lie on a flat bench holding dumbbells above your chest. Arc them out and down with a slight bend in your elbows, then bring them back up.",
    tips: ["Feel the stretch at the bottom", "Keep a soft bend in elbows throughout", "Don't go too deep — stop when you feel tension", "Squeeze the chest at the top"],
    sets: "3–4", reps: "12–15",
  },
  {
    id: "push_up",
    name: "Push-Up",
    category: "chest",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Triceps", "Core", "Front Deltoids"],
    equipment: [],
    difficulty: "Beginner",
    type: "strength",
    description: "The foundational bodyweight chest exercise. Start in plank position with hands slightly wider than shoulders, lower your chest to the floor, then press up.",
    tips: ["Keep your body in a straight line", "Don't let hips sag or pike up", "Full range of motion — chest touches the floor", "Squeeze chest at top"],
    sets: "3–4", reps: "10–20",
  },
  {
    id: "cable_fly",
    name: "Cable Fly",
    category: "chest",
    primaryMuscles: ["Pectorals"],
    secondaryMuscles: ["Front Deltoids"],
    equipment: ["cable_machine"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Stand between cable towers set at shoulder height. Bring handles together in front of your chest with a hugging motion.",
    tips: ["Maintain a slight forward lean", "Slight bend in elbows throughout", "Focus on squeezing the chest at the peak contraction", "Control both phases of the movement"],
    sets: "3–4", reps: "12–15",
  },
  {
    id: "dips_chest",
    name: "Chest Dips",
    category: "chest",
    primaryMuscles: ["Lower Pectorals"],
    secondaryMuscles: ["Triceps", "Front Deltoids"],
    equipment: ["pullup_bar"],
    difficulty: "Intermediate",
    type: "strength",
    description: "On parallel bars, lean forward slightly and lower yourself until your elbows are at 90°. Press back up. The forward lean shifts emphasis to the chest.",
    tips: ["Lean forward for more chest activation", "Control the descent", "Don't lock out elbows fully at the top", "Add weight once bodyweight is easy"],
    sets: "3–4", reps: "8–12",
  },

  // ── BACK ──────────────────────────────────────────────────────────────────
  {
    id: "pull_up",
    name: "Pull-Up",
    category: "back",
    primaryMuscles: ["Lats", "Biceps"],
    secondaryMuscles: ["Rhomboids", "Rear Deltoids", "Core"],
    equipment: ["pullup_bar"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Hang from a pull-up bar with hands shoulder-width apart, palms facing away. Pull your chest to the bar, then lower with control.",
    tips: ["Start from a dead hang", "Drive elbows down and back", "Chin clears the bar at the top", "No kipping — full control"],
    sets: "3–5", reps: "5–10",
  },
  {
    id: "chin_up",
    name: "Chin-Up",
    category: "back",
    primaryMuscles: ["Lats", "Biceps"],
    secondaryMuscles: ["Rhomboids", "Core"],
    equipment: ["pullup_bar"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Like a pull-up but with palms facing you (supinated). Slightly more bicep activation. Pull chin over the bar.",
    tips: ["Supinated grip increases bicep contribution", "Keep core braced", "Full extension at the bottom", "Squeeze at the top"],
    sets: "3–4", reps: "6–10",
  },
  {
    id: "bent_over_row",
    name: "Barbell Bent-Over Row",
    category: "back",
    primaryMuscles: ["Lats", "Rhomboids", "Traps"],
    secondaryMuscles: ["Biceps", "Rear Deltoids", "Erector Spinae"],
    equipment: ["barbell"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Hinge at the hips with a flat back. Pull the bar to your lower chest/upper abdomen, driving elbows back and squeezing the shoulder blades.",
    tips: ["Keep back flat — don't round", "Hinge to about 45° torso angle", "Drive elbows, not hands", "Control the lowering phase"],
    sets: "3–4", reps: "6–10",
  },
  {
    id: "dumbbell_row",
    name: "Single-Arm Dumbbell Row",
    category: "back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Rear Deltoids"],
    equipment: ["dumbbells", "bench"],
    difficulty: "Beginner",
    type: "strength",
    description: "Brace yourself on a bench with one hand and knee. Row the dumbbell up to your hip, leading with your elbow.",
    tips: ["Keep torso parallel to floor", "Row to hip, not to shoulder", "Full stretch at the bottom", "Don't rotate your torso"],
    sets: "3–4", reps: "10–15 each side",
  },
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    category: "back",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Rhomboids", "Rear Deltoids"],
    equipment: ["cable_machine"],
    difficulty: "Beginner",
    type: "strength",
    description: "Sit at the cable machine and pull the bar to your upper chest, driving elbows down and squeezing the lats at the bottom.",
    tips: ["Lean back slightly", "Bring bar to collarbone, not behind neck", "Full stretch at top", "Control the weight going back up"],
    sets: "3–4", reps: "10–12",
  },
  {
    id: "deadlift",
    name: "Deadlift",
    category: "back",
    primaryMuscles: ["Erector Spinae", "Hamstrings", "Glutes"],
    secondaryMuscles: ["Lats", "Traps", "Core", "Quadriceps"],
    equipment: ["barbell"],
    difficulty: "Advanced",
    type: "strength",
    description: "The king of compound lifts. Set up with bar over mid-foot, grab just outside your legs, brace core, and drive through the floor.",
    tips: ["Bar stays close to your body throughout", "Push the floor away, don't pull the bar up", "Hinge, don't squat", "Lockout by squeezing glutes — don't hyperextend"],
    sets: "3–5", reps: "3–8",
  },
  {
    id: "seated_cable_row",
    name: "Seated Cable Row",
    category: "back",
    primaryMuscles: ["Lats", "Rhomboids", "Traps"],
    secondaryMuscles: ["Biceps", "Rear Deltoids"],
    equipment: ["cable_machine"],
    difficulty: "Beginner",
    type: "strength",
    description: "Sit upright at the cable machine and pull the handle to your lower chest/abdomen. Drive elbows back and squeeze shoulder blades.",
    tips: ["Don't lean too far forward or back", "Keep chest up", "Full stretch with shoulder blades protracted at front", "Squeeze at contraction"],
    sets: "3–4", reps: "10–12",
  },

  // ── SHOULDERS ─────────────────────────────────────────────────────────────
  {
    id: "overhead_press",
    name: "Overhead Press",
    category: "shoulders",
    primaryMuscles: ["Front Deltoids", "Side Deltoids"],
    secondaryMuscles: ["Triceps", "Upper Traps", "Core"],
    equipment: ["barbell"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Stand with bar at collarbone height, press straight up overhead until elbows lock out. Lower under control.",
    tips: ["Keep core braced — don't hyperextend lower back", "Bar travels in a slight arc", "Don't shrug at the top", "Full lockout overhead"],
    sets: "3–5", reps: "5–10",
  },
  {
    id: "dumbbell_lateral_raise",
    name: "Lateral Raise",
    category: "shoulders",
    primaryMuscles: ["Side Deltoids"],
    secondaryMuscles: ["Front Deltoids", "Traps"],
    equipment: ["dumbbells"],
    difficulty: "Beginner",
    type: "strength",
    description: "Stand holding dumbbells at your sides. Raise arms out to shoulder height, leading with elbows, then lower slowly.",
    tips: ["Lead with elbows, not wrists", "Slight bend in elbows throughout", "Don't go above shoulder height", "Slow eccentric for more gains"],
    sets: "3–4", reps: "12–20",
  },
  {
    id: "face_pull",
    name: "Face Pull",
    category: "shoulders",
    primaryMuscles: ["Rear Deltoids", "Rhomboids"],
    secondaryMuscles: ["External Rotators", "Traps"],
    equipment: ["cable_machine"],
    difficulty: "Beginner",
    type: "strength",
    description: "Set the cable at face height. Pull the rope attachment to your face with elbows flared high and wide.",
    tips: ["Keep elbows above wrists", "Pull to your nose/eyes level", "Squeeze rear delts at end", "Light weight, high rep for joint health"],
    sets: "3–4", reps: "15–20",
  },
  {
    id: "arnold_press",
    name: "Arnold Press",
    category: "shoulders",
    primaryMuscles: ["Front Deltoids", "Side Deltoids"],
    secondaryMuscles: ["Triceps", "Rear Deltoids"],
    equipment: ["dumbbells"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Start with dumbbells in front of you, palms facing you. As you press up, rotate palms outward. Reverse the motion on the way down.",
    tips: ["Full rotation from palm-in to palm-forward", "Slow and controlled", "Full range of motion", "Great for overall shoulder development"],
    sets: "3–4", reps: "10–12",
  },
  {
    id: "front_raise",
    name: "Front Raise",
    category: "shoulders",
    primaryMuscles: ["Front Deltoids"],
    secondaryMuscles: ["Side Deltoids", "Traps"],
    equipment: ["dumbbells"],
    difficulty: "Beginner",
    type: "strength",
    description: "Hold dumbbells in front of your thighs. Raise both arms forward to shoulder height, keeping a slight bend in elbows.",
    tips: ["Don't swing or use momentum", "Keep wrists neutral", "Stop at shoulder height", "Lower slowly for more tension"],
    sets: "3", reps: "12–15",
  },

  // ── ARMS ──────────────────────────────────────────────────────────────────
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    category: "arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Brachialis", "Brachioradialis"],
    equipment: ["barbell"],
    difficulty: "Beginner",
    type: "strength",
    description: "Stand holding a barbell with an underhand grip. Curl the bar toward your shoulders, keeping elbows fixed at your sides.",
    tips: ["Don't swing your back", "Full range of motion — full extension at bottom", "Squeeze bicep at the top", "Keep elbows pinned to your sides"],
    sets: "3–4", reps: "8–12",
  },
  {
    id: "dumbbell_curl",
    name: "Dumbbell Curl",
    category: "arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Brachialis"],
    equipment: ["dumbbells"],
    difficulty: "Beginner",
    type: "strength",
    description: "Hold dumbbells at your sides, palms facing forward. Curl both or alternating, bringing dumbbells to shoulder height.",
    tips: ["Supinate wrist at top for full contraction", "Keep upper arms stationary", "Full extension at the bottom", "Controlled tempo"],
    sets: "3–4", reps: "10–15",
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    category: "arms",
    primaryMuscles: ["Brachialis", "Brachioradialis"],
    secondaryMuscles: ["Biceps"],
    equipment: ["dumbbells"],
    difficulty: "Beginner",
    type: "strength",
    description: "Hold dumbbells with neutral grip (palms facing each other). Curl both to shoulder height simultaneously or alternating.",
    tips: ["Neutral grip targets the brachialis", "Don't swing", "Slow on the way down", "Keep elbows pinned to sides"],
    sets: "3", reps: "10–15",
  },
  {
    id: "tricep_dips",
    name: "Tricep Dips",
    category: "arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Front Deltoids", "Chest"],
    equipment: [],
    difficulty: "Beginner",
    type: "strength",
    description: "With hands on a bench or chair behind you, lower yourself by bending your elbows, then press back up.",
    tips: ["Keep elbows pointing back, not out", "Don't let shoulders rise up", "Full range of motion", "Slow the eccentric for more tension"],
    sets: "3–4", reps: "10–15",
  },
  {
    id: "skull_crusher",
    name: "Skull Crusher",
    category: "arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: ["barbell", "bench"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Lie on a bench holding a barbell or EZ bar above your face. Lower the bar toward your forehead by bending elbows, then extend.",
    tips: ["Keep upper arms perpendicular to the floor", "Elbows shouldn't flare out", "Control the descent carefully", "Can also use dumbbells"],
    sets: "3–4", reps: "10–12",
  },
  {
    id: "tricep_pushdown",
    name: "Cable Tricep Pushdown",
    category: "arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: ["cable_machine"],
    difficulty: "Beginner",
    type: "strength",
    description: "Stand at a cable machine with a bar or rope attachment at the top. Push the attachment down by extending your elbows.",
    tips: ["Keep elbows at your sides", "Full extension at the bottom", "Squeeze triceps at lockout", "Rope gives extra range of motion"],
    sets: "3–4", reps: "12–15",
  },
  {
    id: "preacher_curl",
    name: "Preacher Curl",
    category: "arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Brachialis"],
    equipment: ["barbell", "bench"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Rest your upper arms on the preacher bench pad. Curl the weight up with a full range of motion.",
    tips: ["Full extension at the bottom", "Don't swing or jerk", "Isolates the bicep by removing swing", "Use moderate weight"],
    sets: "3", reps: "10–12",
  },

  // ── LEGS ──────────────────────────────────────────────────────────────────
  {
    id: "squat",
    name: "Barbell Back Squat",
    category: "legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Erector Spinae"],
    equipment: ["barbell"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Place the bar on your upper back, feet shoulder-width apart. Descend until thighs are parallel to the floor, then drive back up.",
    tips: ["Keep chest up and core braced", "Knees track over toes", "Full depth — thighs parallel or below", "Drive through your heels"],
    sets: "3–5", reps: "5–8",
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    category: "legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Core", "Hamstrings"],
    equipment: ["dumbbells", "kettlebells"],
    difficulty: "Beginner",
    type: "strength",
    description: "Hold a dumbbell or kettlebell at your chest. Squat down between your knees with elbows touching the inside of your knees at the bottom.",
    tips: ["Great beginner squat", "Keep weight at chest", "Elbows touch knees at bottom", "Drive through full foot"],
    sets: "3–4", reps: "10–15",
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    category: "legs",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Erector Spinae", "Core"],
    equipment: ["barbell"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Stand holding a barbell. Hinge at the hips, pushing them back as you lower the bar down your legs. Feel the hamstring stretch, then drive hips forward.",
    tips: ["Push hips back, don't bend knees much", "Bar stays close to your legs", "Feel the stretch in hamstrings", "Soft bend in knees throughout"],
    sets: "3–4", reps: "8–12",
  },
  {
    id: "leg_press_machine",
    name: "Leg Press",
    category: "legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: ["leg_press"],
    difficulty: "Beginner",
    type: "strength",
    description: "Sit in the leg press machine. Push the platform away by extending your legs, then slowly lower back down.",
    tips: ["Don't lock out knees at the top", "Keep lower back pressed into seat", "Foot placement affects muscle emphasis", "Control the descent"],
    sets: "3–4", reps: "10–15",
  },
  {
    id: "lunge",
    name: "Walking Lunge",
    category: "legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core", "Calves"],
    equipment: [],
    difficulty: "Beginner",
    type: "strength",
    description: "Step forward with one foot and lower your back knee toward the ground. Push up and step the back foot forward to repeat.",
    tips: ["Front knee stays behind toes", "Torso stays upright", "Lower back knee, don't slam it", "Add dumbbells for progression"],
    sets: "3", reps: "10–12 per leg",
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    category: "legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: ["bench", "dumbbells"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Rear foot elevated on a bench, front foot forward. Lower until front thigh is parallel to the floor.",
    tips: ["Front foot should be far enough forward", "Torso can lean slightly forward", "Drive through front heel", "One of the best unilateral leg exercises"],
    sets: "3–4", reps: "8–12 per leg",
  },
  {
    id: "leg_curl",
    name: "Lying Leg Curl",
    category: "legs",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Calves"],
    equipment: ["cable_machine"],
    difficulty: "Beginner",
    type: "strength",
    description: "Lie face down on the machine. Curl your heels toward your glutes, pause at the top, then lower slowly.",
    tips: ["Full range of motion", "Don't let hips rise off the pad", "Slow eccentric", "Squeeze hamstrings at the top"],
    sets: "3–4", reps: "10–15",
  },
  {
    id: "calf_raise",
    name: "Calf Raise",
    category: "legs",
    primaryMuscles: ["Calves (Gastrocnemius)"],
    secondaryMuscles: ["Soleus"],
    equipment: [],
    difficulty: "Beginner",
    type: "strength",
    description: "Stand on a step or flat surface. Rise up on your toes as high as possible, then lower your heel below the step for full stretch.",
    tips: ["Full range of motion is key", "Slow on the way down", "Can be loaded with dumbbells", "High reps respond better for calves"],
    sets: "4", reps: "15–25",
  },

  // ── GLUTES ────────────────────────────────────────────────────────────────
  {
    id: "hip_thrust",
    name: "Barbell Hip Thrust",
    category: "glutes",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: ["barbell", "bench"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Sit with upper back on a bench, bar across your hips. Drive hips up until your torso is parallel to the floor.",
    tips: ["Drive hips to full extension", "Tuck chin and press back into bench", "Squeeze glutes hard at top", "The best isolation for glutes"],
    sets: "3–4", reps: "10–15",
  },
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    category: "glutes",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: [],
    difficulty: "Beginner",
    type: "strength",
    description: "Lie on your back with knees bent. Drive your hips up by squeezing your glutes, hold for a second, then lower.",
    tips: ["Squeeze glutes hard at the top", "Don't hyperextend the lower back", "Single-leg version increases difficulty", "Add weight once bodyweight is easy"],
    sets: "3–4", reps: "15–20",
  },
  {
    id: "cable_kickback",
    name: "Cable Glute Kickback",
    category: "glutes",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: ["cable_machine"],
    difficulty: "Beginner",
    type: "strength",
    description: "Attach an ankle strap to the cable machine. Kick your leg back and up, squeezing the glute at the top.",
    tips: ["Keep your core braced", "Squeeze glute at full extension", "Don't hyperextend lower back", "Slow and controlled"],
    sets: "3", reps: "15 per leg",
  },
  {
    id: "sumo_squat",
    name: "Sumo Squat",
    category: "glutes",
    primaryMuscles: ["Glutes", "Inner Thighs"],
    secondaryMuscles: ["Quadriceps", "Hamstrings"],
    equipment: ["dumbbells", "kettlebells"],
    difficulty: "Beginner",
    type: "strength",
    description: "Wide stance with toes pointed out. Hold a weight at your chest or between your legs. Squat down keeping your chest tall.",
    tips: ["Knees track over toes throughout", "Deeper stance = more glute activation", "Drive through heels", "Keep torso upright"],
    sets: "3–4", reps: "10–15",
  },
  {
    id: "donkey_kick",
    name: "Donkey Kick",
    category: "glutes",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Core"],
    equipment: [],
    difficulty: "Beginner",
    type: "strength",
    description: "On all fours, kick one leg up toward the ceiling while keeping the knee bent at 90°. Squeeze your glute at the top.",
    tips: ["Keep hips level — don't rotate", "Core stays tight", "Squeeze glute at top", "Add ankle weights for more challenge"],
    sets: "3", reps: "15–20 per leg",
  },

  // ── CORE ──────────────────────────────────────────────────────────────────
  {
    id: "plank",
    name: "Plank",
    category: "core",
    primaryMuscles: ["Core", "Transverse Abdominis"],
    secondaryMuscles: ["Shoulders", "Glutes"],
    equipment: [],
    difficulty: "Beginner",
    type: "strength",
    description: "Hold a straight-body position on your forearms or hands. Maintain a rigid plank from head to heels.",
    tips: ["Keep hips level — don't sag or pike", "Breathe steadily", "Squeeze glutes and brace abs", "Look at the floor"],
    duration: "30–60 sec",
  },
  {
    id: "crunch",
    name: "Crunch",
    category: "core",
    primaryMuscles: ["Rectus Abdominis"],
    secondaryMuscles: ["Obliques"],
    equipment: [],
    difficulty: "Beginner",
    type: "strength",
    description: "Lie on your back with knees bent. Curl your shoulders off the floor by contracting your abs, then lower.",
    tips: ["Don't pull your neck with your hands", "Exhale on the way up", "Feel the abs working, not hip flexors", "Full contraction at top"],
    sets: "3–4", reps: "15–25",
  },
  {
    id: "russian_twist",
    name: "Russian Twist",
    category: "core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Rectus Abdominis"],
    equipment: [],
    difficulty: "Beginner",
    type: "strength",
    description: "Sit with knees bent and feet off the floor. Rotate your torso side to side, touching the floor on each side.",
    tips: ["Keep feet off the floor for more challenge", "Rotate from the torso, not arms", "Add a weight for progression", "Move slowly and controlled"],
    sets: "3", reps: "20 total",
  },
  {
    id: "hanging_leg_raise",
    name: "Hanging Leg Raise",
    category: "core",
    primaryMuscles: ["Lower Abs", "Hip Flexors"],
    secondaryMuscles: ["Obliques", "Grip"],
    equipment: ["pullup_bar"],
    difficulty: "Advanced",
    type: "strength",
    description: "Hang from a pull-up bar. Raise your legs to 90° or higher with control, then lower slowly.",
    tips: ["Avoid swinging", "Tilt pelvis back to engage lower abs", "Slow and controlled", "Bent-knee version for beginners"],
    sets: "3–4", reps: "10–15",
  },
  {
    id: "ab_wheel",
    name: "Ab Wheel Rollout",
    category: "core",
    primaryMuscles: ["Core", "Transverse Abdominis"],
    secondaryMuscles: ["Shoulders", "Lats"],
    equipment: [],
    difficulty: "Advanced",
    type: "strength",
    description: "Kneel holding an ab wheel. Roll it forward as far as you can while keeping your back flat, then pull it back.",
    tips: ["Keep your back flat throughout", "Brace your core before rolling", "Don't let hips drop", "Start with half-rollouts"],
    sets: "3", reps: "8–12",
  },
  {
    id: "mountain_climber",
    name: "Mountain Climber",
    category: "core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders", "Legs", "Hip Flexors"],
    equipment: [],
    difficulty: "Beginner",
    type: "plyometric",
    description: "Start in a push-up position. Rapidly alternate driving each knee toward your chest while keeping your body stable.",
    tips: ["Keep hips down — don't pike up", "Core braced throughout", "Can do slow for more control", "Great as a cardio-core combo"],
    sets: "3", duration: "30 sec",
  },

  // ── CARDIO ────────────────────────────────────────────────────────────────
  {
    id: "running",
    name: "Running",
    category: "cardio",
    primaryMuscles: ["Legs", "Core", "Cardiovascular System"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "Beginner",
    type: "cardio",
    description: "One of the most natural and effective forms of cardio. Builds endurance, burns calories, and improves heart health.",
    tips: ["Land with foot under your hip, not in front", "Relax your shoulders", "Breathe from your belly", "Build mileage slowly — max 10% per week"],
    duration: "20–60 min",
  },
  {
    id: "jump_rope_exercise",
    name: "Jump Rope",
    category: "cardio",
    primaryMuscles: ["Calves", "Cardiovascular System"],
    secondaryMuscles: ["Shoulders", "Core", "Legs"],
    equipment: ["jump_rope"],
    difficulty: "Beginner",
    type: "cardio",
    description: "An excellent full-body cardio workout. Burns more calories per minute than most cardio exercises.",
    tips: ["Jump just high enough for the rope to pass", "Land softly on the balls of your feet", "Keep elbows close to your sides", "Start with intervals"],
    duration: "10–20 min",
  },
  {
    id: "cycling_exercise",
    name: "Cycling",
    category: "cardio",
    primaryMuscles: ["Quadriceps", "Glutes", "Cardiovascular System"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    equipment: ["stationary_bike"],
    difficulty: "Beginner",
    type: "cardio",
    description: "Low-impact cardio that's great for all fitness levels. Can be done on a bike outdoors or a stationary bike.",
    tips: ["Seat height should allow slight knee bend at bottom", "Pedal at a comfortable cadence", "Vary resistance and speed", "Great for active recovery too"],
    duration: "20–60 min",
  },
  {
    id: "rowing",
    name: "Rowing",
    category: "cardio",
    primaryMuscles: ["Back", "Arms", "Legs", "Cardiovascular System"],
    secondaryMuscles: ["Core"],
    equipment: ["rowing_machine"],
    difficulty: "Intermediate",
    type: "cardio",
    description: "Full-body cardio that works 86% of your muscles. Excellent for fitness and calorie burn.",
    tips: ["Drive with legs first, then lean back, then pull arms", "60% legs, 20% lean, 20% arms", "Keep a straight back throughout", "Aim for a smooth stroke rate"],
    duration: "15–30 min",
  },
  {
    id: "burpee",
    name: "Burpee",
    category: "cardio",
    primaryMuscles: ["Full Body"],
    secondaryMuscles: [],
    equipment: [],
    difficulty: "Intermediate",
    type: "plyometric",
    description: "From standing, drop to the floor, do a push-up, jump your feet forward, then explosively jump up with arms overhead.",
    tips: ["Land softly from the jump", "Can modify by stepping instead of jumping", "Keep core tight throughout", "Great for metabolic conditioning"],
    sets: "3–4", reps: "10–15",
  },
  {
    id: "box_jump",
    name: "Box Jump",
    category: "cardio",
    primaryMuscles: ["Quadriceps", "Glutes", "Calves"],
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: [],
    difficulty: "Intermediate",
    type: "plyometric",
    description: "Start in a squat position, then explosively jump onto a box or elevated surface. Step down carefully.",
    tips: ["Land softly with knees bent", "Start with a low box", "Use your arms for momentum", "Step down — don't jump down"],
    sets: "3–4", reps: "8–10",
  },

  // ── FULL BODY ─────────────────────────────────────────────────────────────
  {
    id: "clean_and_press",
    name: "Dumbbell Clean & Press",
    category: "full_body",
    primaryMuscles: ["Shoulders", "Legs", "Core"],
    secondaryMuscles: ["Back", "Triceps"],
    equipment: ["dumbbells"],
    difficulty: "Intermediate",
    type: "strength",
    description: "Squat down, grab dumbbells, then explosively clean them to shoulder height and press overhead.",
    tips: ["Use leg drive for the clean", "Catch the weight at shoulder height", "Control throughout", "Great for power and conditioning"],
    sets: "3–4", reps: "6–10",
  },
  {
    id: "kettlebell_swing",
    name: "Kettlebell Swing",
    category: "full_body",
    primaryMuscles: ["Glutes", "Hamstrings"],
    secondaryMuscles: ["Core", "Shoulders", "Back"],
    equipment: ["kettlebells"],
    difficulty: "Intermediate",
    type: "plyometric",
    description: "Hinge at the hips and swing the kettlebell between your legs. Drive your hips forward explosively to swing it to chest height.",
    tips: ["It's a hip hinge, not a squat", "Let the bell float at the top", "Squeeze glutes at the top", "Keep back flat throughout"],
    sets: "3–4", reps: "15–20",
  },
  {
    id: "turkish_getup",
    name: "Turkish Get-Up",
    category: "full_body",
    primaryMuscles: ["Core", "Shoulders"],
    secondaryMuscles: ["Glutes", "Legs"],
    equipment: ["dumbbells", "kettlebells"],
    difficulty: "Advanced",
    type: "strength",
    description: "Lie holding a weight above you, then go from lying to standing while keeping the weight locked out overhead.",
    tips: ["Master the movement without weight first", "Keep eyes on the weight throughout", "Take each step deliberately", "Excellent for shoulder stability"],
    sets: "3", reps: "3–5 per side",
  },
  {
    id: "thruster",
    name: "Thruster",
    category: "full_body",
    primaryMuscles: ["Quadriceps", "Glutes", "Shoulders"],
    secondaryMuscles: ["Triceps", "Core", "Back"],
    equipment: ["barbell"],
    difficulty: "Advanced",
    type: "strength",
    description: "Front squat into an overhead press in one fluid motion. As you drive out of the squat, use that momentum to press the bar overhead.",
    tips: ["Timing is key — use the squat to power the press", "Keep core braced", "Full depth squat", "Arms fully extended overhead at top"],
    sets: "3–4", reps: "6–10",
  },

  // ── FLEXIBILITY ───────────────────────────────────────────────────────────
  {
    id: "hip_flexor_stretch",
    name: "Hip Flexor Stretch",
    category: "flexibility",
    primaryMuscles: ["Hip Flexors"],
    secondaryMuscles: ["Quads"],
    equipment: [],
    difficulty: "Beginner",
    type: "flexibility",
    description: "Kneel on one knee. Push your hips forward until you feel a stretch in the front of your rear hip.",
    tips: ["Squeeze the rear glute", "Keep torso upright", "Hold 30–60 seconds", "Great for desk workers and runners"],
    duration: "30–60 sec per side",
  },
  {
    id: "downward_dog",
    name: "Downward Dog",
    category: "flexibility",
    primaryMuscles: ["Hamstrings", "Calves", "Shoulders"],
    secondaryMuscles: ["Core"],
    equipment: ["yoga_mat"],
    difficulty: "Beginner",
    type: "flexibility",
    description: "From a push-up position, push your hips up and back to form an inverted V. Press your heels toward the floor.",
    tips: ["Pedal feet alternately to warm up", "Push through all fingers", "Hips as high as comfortable", "Breathe deeply"],
    duration: "30–60 sec",
  },
  {
    id: "pigeon_pose",
    name: "Pigeon Pose",
    category: "flexibility",
    primaryMuscles: ["Glutes", "Hip Rotators"],
    secondaryMuscles: ["Hip Flexors"],
    equipment: ["yoga_mat"],
    difficulty: "Intermediate",
    type: "flexibility",
    description: "From a push-up position, bring one knee forward and out to the side. Lower the rear leg flat and fold forward.",
    tips: ["Support yourself if hips don't reach floor", "Breathe into the stretch", "Hold 60–120 seconds per side", "Excellent for tight hips"],
    duration: "60–120 sec per side",
  },
  {
    id: "world_greatest_stretch",
    name: "World's Greatest Stretch",
    category: "flexibility",
    primaryMuscles: ["Hip Flexors", "Thoracic Spine", "Hamstrings"],
    secondaryMuscles: ["Glutes", "Core"],
    equipment: [],
    difficulty: "Beginner",
    type: "flexibility",
    description: "Lunge forward, place same-side hand down, rotate upper body opening toward the ceiling. Alternate sides.",
    tips: ["Move slowly through each position", "Feel each stretch", "Great for warming up", "Can be part of a mobility routine"],
    duration: "5 reps per side",
  },
  {
    id: "cat_cow",
    name: "Cat-Cow Stretch",
    category: "flexibility",
    primaryMuscles: ["Spine", "Core"],
    secondaryMuscles: ["Back", "Neck"],
    equipment: ["yoga_mat"],
    difficulty: "Beginner",
    type: "flexibility",
    description: "On all fours, alternate between arching your back up (cat) and dropping it down with chest lifted (cow).",
    tips: ["Breathe: exhale during cat, inhale during cow", "Move slowly and mindfully", "Great for spinal mobility", "Excellent morning stretch"],
    duration: "10 reps",
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function getExercisesByCategory(category: ExerciseCategory): Exercise[] {
  return EXERCISES.filter((e) => e.category === category);
}

export function searchExercises(query: string): Exercise[] {
  const q = query.toLowerCase();
  return EXERCISES.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.primaryMuscles.some((m) => m.toLowerCase().includes(q)) ||
      e.category.includes(q)
  );
}

export function getExercisesByEquipment(equipmentIds: string[]): Exercise[] {
  if (equipmentIds.length === 0) return EXERCISES;
  return EXERCISES.filter((e) =>
    e.equipment.length === 0 || e.equipment.some((eq) => equipmentIds.includes(eq))
  );
}
